version: '3'
services:
  dispatcher:
    image: ${DISPATCHER_IMAGE}
    ports:
      - 8888:5637
    environment:
      - PORT=5637
      - STORAGE_HOST=checkpoint
      - STORAGE_PORT=6379
      - REFRESH_TIME=30
      - EXPIRE_TIME=45
    networks:
      - servers
  checkpoint:
    image: redis:6-alpine
    ports:
      - 16379:6379
    networks:
      - servers
networks:
  servers:
    external:
      name: servers